# Generated by Django 5.2.8 on 2026-02-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostOffice_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('driver', 'Driver'), ('staff', 'Staff'), ('manager', 'Manager')], default='client', max_length=16),
        ),
    ]
