# Generated by Django 5.2.7 on 2025-11-01 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_status', models.CharField(max_length=50)),
                ('invoice_type', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('invoice_datetime', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash'), ('Transfer', 'Transfer')], max_length=20)),
                ('morada', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
    ]
