# Generated by Django 5.2.7 on 2025-11-08 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostOffice_App', '0001_initial'),
    ]

    operations = [
    ]
