# Generated by Django 5.2.7 on 2025-11-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostOffice_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='id',
            new_name='id_invoice',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='morada',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contact',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(default='Standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('Transfer', 'Transfer')], default='Credit Card', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
